### ISSUE TITLE
[Starknet - Front]  Connect Wallet + Nav Bar

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-locker#1]
**Description**
---
Create a fully functional and styled navigation bar for the dApp. The navigation should allow users to move between the HomePage, Locker, and Dashboard.

**Acceptance Criteria**
---

- [ ] Create a `Navbar` component with links to `/`, `/locker`, and `/dashboard`.
- [ ] Highlight the active page in the navigation links.
- [ ] Add a "Connect Wallet" button for starknet wallet, should be compatible with Argent and Braavos.
- [ ] Ensure the Navbar is responsive for desktop at least (mobile optional)

**Additional context**
---
The Navbar should have distinct styles for the active link and hover states. Use TailwindCSS and [dapp](https://github.com/Carbonable/carbonable-home) as an example for styling.

[ Medium Difficulty - Frontend, Starknet dep ]

**Comment by NueloSE** [comment]
@julienbrs kindly assign me this task
Mind if I take this issue?

**Comment by julienbrs** [comment]
Hi, I'm assigning it to you @NueloSE. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the isue.
You can ping me if needed on TG

**Comment by jrmncos** [comment]
hey team, I'm a SSR fullstack developer, I already implemented the 'Connect Wallet' button in a personal application. I can do it for this one + the rest of the requirements
