### ISSUE TITLE
[Front] Improve Home Page Design and Add Branding

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-locker#4]
**Description**
---
Enhance the Home Page  to include better styling, a logo, and a professional look. The page should act as a welcoming entry point for the dApp while maintaining simplicity.

**Acceptance Criteria**
---

- [ ] Add a logo or placeholder image at the top of the Home Page.
- [ ] Add descriptive text explaining the purpose of the dApp in a visually appealing format.
- [ ] Improve the overall styling, Use TailwindCSS and [dapp](https://github.com/Carbonable/carbonable-home) as an example.

**Additional context**
---
[ Easy Difficulty - Frontend ]

**Comment by DanielEmmanuel1** [comment]
Can I take this issue?

I'm a Full-Stack developer with sufficient experirnce in building pixel perfect UI, can i be assigened this please

ETA: 24 hrs

**Comment by julienbrs** [comment]
Hi, I've assigned that issue to @SudiptaPaul-31, as you are already assigned to an issue @DanielEmmanuel1. You can ping me if you got any question, and please join TG if not already done: https://t.me/carbonableOD

**Comment by DanielEmmanuel1** [comment]
Sure will, I'll get right on it

**Comment by Jimmy-csc** [comment]
Could I be assigned to this?

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. To enhance the Home Page, I’d add a logo or placeholder image at the top for a professional look. Below it, I’d include clear, concise text explaining the dApp’s purpose in an easy-to-read format. Using TailwindCSS, I’d improve the styling with a clean, modern design, focusing on simplicity and responsiveness. The goal is to create a welcoming and user-friendly entry point for the dApp, making it visually appealing without cluttering the page.  I would really love to be assigned this issue and work on this project.
