### ISSUE TITLE
[Cairo Contract] - Impl LockerHandler Interface Functions

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-locker#5]
**Description**
---
Implement the missing functions in the LockerHandler interface to ensure users can interact fully with the locker system.

**Acceptance Criteria**
---

- [ ] Implement lock_credits, is_lock_expired, is_lock_offsettable, offset_credits, get_lock, get_user_locks, get_locked_credits, get_total_locks.
- [ ] Add complete and complex test coverage
- [ ] Emit events when needed

**Additional context**
---
[ Hard Difficulty - Cairo ]

**Comment by ibrahimtaib** [comment]
hi, can I please be assigned to this issue? I would implement the functions accordingly to what the offsetter from the main protocol is doing.
thanks a lot

**Comment by SoarinSkySagar** [comment]
May I work on this issue @julienbrs?

I will write the functions as expected and add extensive tests for the same. 

eta: 3 days

**Comment by TropicalDog17** [comment]
Hi, I have experience in various open source Rust projects and also previously work on a Carbonable issue.

https://github.com/carbonable-labs/svgenerator/pull/10

https://github.com/paradigmxyz/reth/commits/main/?author=TropicalDog17

https://github.com/foundry-rs/foundry/commits/master/?author=TropicalDog17

I also have some experience in Cairo, and Solidity: https://github.com/kfastov/worldcoin-bridge-linea/pulls?q=is%3Apr+author%3ATropicalDog17+is%3Aclosed

**Comment by julienbrs** [comment]
Hi, I'm assigning it to @ibrahimtaib as they were the first one to ask. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the isue

**Comment by ibrahimtaib** [comment]
asking through OD, thanks for the assignation
