### ISSUE TITLE
[Cairo Contract] - Implement Early Withdrawal Logic

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-locker#6]
**Description**
---
Implement the penalty offset logic allowing early termination of locks under strict conditions. Add an admin function to configure the penalty calculation. Locks can only be partially withdrawn once the associated carbon credits have the status "audited." Any remaining credits will be offset immediately for a predefined recipient (e.g., an NGO) by calling the offsetter for that amount.

**Acceptance Criteria**
---

- [ ]  Implement terminate_lock_with_penalty:
    - Check if the credits are "audited" before allowing withdrawal.
    - If audited:
           -  Allow the user to withdraw a specified portion.
            - Offset the remaining credits immediately. It will be on behalf of an other recipient.
    - If not audited, deny the withdrawal.
- Configure penalty logic using an admin-managed multiplier or percentage. Ensure penalties decrease as the lock expiration approaches.
- [ ] Add complete and complex test coverage
- [ ]  Emit events

**Additional context**
---
Simplest penalty function would be:
`Penalty Amount=Withdraw Amount×Penalty Multiplier×Remaining Lock Time / Total Lock Time`​.
Better penalty function can be used.
[ Medium Difficulty - Cairo ]

**Comment by lascarbz** [comment]
Hello, I'd like to work on this issue please. I've looked into the vintage struct of the protocol so I know how to handle it

**Comment by lascarbz** [comment]
Also asking on OD

**Comment by julienbrs** [comment]
Hi, I'm assigning it to @lascarbz. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the isue.
You can ping me if needed
