### ISSUE TITLE
[Cairo Contract] - Impl admin functions

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-locker#8]
**Description**
---
Implement admin functions that can be called only by owner. Setup OWNER accordingly

**Acceptance Criteria**
---

- [ ] Implement getter and setter to manage offsetter_address, nft_component_address
- [ ] Emits events accordingly
- [ ] Add complete and complex test coverage

**Additional context**
---
[ Easy Difficulty - Cairo ]

**Comment by petersdt** [comment]
I’d like to resolve this.

i am a frontend developer and have experience writing and testing smart contract using cairo and solidity

**Comment by emarc99** [comment]
Let me do this. I have solidity programming experience, completed starklings, node guardians quests and contributed successfully to a cairo project through OD.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Rust ,Cairo  projects like chainevents , arkprojects , starknet  etc  .   please /assign  this issue .
Thank You

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by julienbrs** [comment]
Hi, I'm assigning it to @SoarinSkySagar as they were the first one to ask. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the isue.

**Comment by SoarinSkySagar** [comment]
> Hi, I'm assigning it to @SoarinSkySagar as they were the first one to ask. Please join TG to discuss about it if needed: https://t.me/carbonableOD Issue might be reassigned during ODHack if the contributor drops the isue. Please @SoarinSkySagar ask the assignation through OnlyDust website

thanks for assigning @julienbrs
